version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ecg_postgres
    restart: always 
    environment:
      POSTGRES_USER: ${DATABASE_USER:-ecg_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-ecg_pass}
      POSTGRES_DB: ${DATABASE_NAME:-ecg_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-ecg_user} -d ${DATABASE_NAME:-ecg_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:

    build: .
    container_name: ekg_backend
    restart: always
    ports:
    - "5000:5000"
    environment:
      DATABAASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER:-ecg_user} 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-ecg_pass}
      DATABASE_NAME: ${DATABASE_NAME:-ecg_db}
    depends_on:
        postgres:
          condition: service_healthy

volumes:
  postgres_data:
    driver: local